/** Shared defaults; array factories keep selector instances isolated. */
export const dataSelectDefaults = {
  data: () => [],
  selectedData: () => [],
  columns: () => [],
  title: '选择数据',
  subtitle: '',
  placeholder: '请选择',
  searchPlaceholder: '请输入关键词',
  filterPlaceholder: '请选择分类',
  filterKey: 'type',
  filterOptions: () => [],
  rowKey: 'id',
  labelKey: 'label',
  descriptionKey: undefined,
  disabledKey: 'disabled',
  childrenKey: 'children',
  resultField: 'data',
  totalField: 'total',
  dialogWidth: 'xl',
  fullscreen: false,
  pageSize: 10,
  pageSizes: () => [10, 20, 30, 50],
  showSearch: true,
  clearable: true,
  disabled: false,
  reserveSelected: true,
  treeCheckStrictly: true,
  maxTagCount: 2,
  emptyText: '暂无数据',
  emptyDescription: ''
} as const
